CXXFLAGS=-std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
CFLAGS=-std=c99 -pedantic -Wall -Wextra -Werror -ansi -Write-strings

test_matrix: test_matrix.cpp
	g++ $(CXXFLAGS) test_matrix.cpp -o test_matrix

clean:
	/bin/rm test_matrix
